language: rust
rust: stable
sudo: false
script:
  - cargo test --all --features "toml_config yaml_config json_config"
  - cargo build
  # No idea how to fix this, since we don't depend on futures-preview directly.
  # - rustdoc --test README.md --extern irc=target/debug/libirc.rlib -L target/debug/deps --edition 2018
  - cargo run --example build-bot
notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.pdgn.co:6697/#commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
