language: rust
rust: stable
sudo: false
script:
  - chmod +x mktestconfig.sh
  - ./mktestconfig.sh
  - cargo build --verbose
  - rustdoc --test README.md --extern irc=target/debug/libirc.rlib -L target/debug/deps
  - cargo test --verbose --features "toml yaml"
  - cargo test --doc
  - cargo test --verbose --no-default-features
  - cargo run --bin build-bot
notifications:
  email: false
  irc:
    channels:
      - "ircs://irc.pdgn.co:6697/#commits"
    template:
      - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
    skip_join: true
