[package]

name = "irc"
version = "0.11.0"
description = "A simple, thread-safe IRC client library."
authors = ["Aaron Weiss <aaronweiss74@gmail.com>"]
license = "CC0-1.0"
keywords = ["irc", "client", "thread-safe"]
documentation = "http://aatxe.github.io/irc/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[features]

default = ["ctcp", "encode", "ssl"]
ctcp = []
encode = ["encoding"]
ssl = ["openssl"]
nochanlists = []

[dependencies.rustc-serialize]
version = "0.3"

[dependencies.time]
version = "0.1"

[dependencies.encoding]
version = "0.2"
optional = true

[dependencies.openssl]
version = "0.7"
optional = true
