[package]
name = "irc"
version = "0.13.4"
description = "the irc crate â€“ usable, async IRC for Rust "
authors = ["Aaron Weiss <awe@pdgn.co>"]
license = "MPL-2.0"
keywords = ["irc", "client", "thread-safe", "async", "tokio", "protocol"]
categories = ["asynchronous", "network-programming"]
documentation = "https://docs.rs/irc/"
repository = "https://github.com/aatxe/irc"
readme = "README.md"

[badges]
travis-ci = { repository = "aatxe/irc" }

[features]
default = ["ctcp", "toml"]
ctcp = []
nochanlists = []
json = ["serde_json"]
yaml = ["serde_yaml"]

[dependencies]
bufstream = "0.1"
bytes = "0.4"
chrono = "0.4"
encoding = "0.2"
failure = "0.1"
futures = "0.1"
log = "0.3"
native-tls = "0.1"
serde = "1.0"
serde_derive = "1.0"
serde_json = { version = "1.0", optional = true }
serde_yaml = { version = "0.7", optional = true }
tokio-core = "0.1"
tokio-io = "0.1"
tokio-mockstream = "1.1"
tokio-timer = "0.1"
tokio-tls = "0.1"
toml = { version = "0.4", optional = true }

[dev-dependencies]
args = "2.0"
getopts = "0.2"
